### ISSUE TITLE
The netlib dependency is "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly()

### ISSUE THREAD

**Issue by qiuxin2012** [amplab/ml-matrix#11]
The netlib dependency is "com.github.fommil.netlib" % "all" % "1.1.2" pomOnly(), pomOnly() is missing in this project's build.sbt. 
My project depends on keystoneml, and keystoneml depends on ml-matrix. So maven wants to download com.github.fommil.netlib.all.jar:1.1.2 and get a failure. No jar file in com.github.fommil.netlib.all, only a pom.

**Comment by shivaram** [comment]
Thanks for reporting this - Just to confirm, your problem will be fixed if the ml-matrix build.sbt is changed to use `pomOnly`?

**Comment by qiuxin2012** [comment]
@shivaram  Yes, I'm sure.  I added `<type>pom<type>` to ml-matrix's pom.xml in my local .m2/repository, then my project could build successfully. 
In fommil's [https://github.com/fommil/netlib-java](url) pomOnly is the right way for sbt.

**Comment by shivaram** [comment]
0.1.1 has now been pushed to maven. Let me know if things work now.
